hookfunction(require(game:GetService("ReplicatedStorage").Effect.Container.Death), function() return end)
hookfunction(require(game:GetService("ReplicatedStorage").Effect.Container.Respawn), function() return end)
hookfunction(require(game:GetService("ReplicatedStorage"):WaitForChild("GuideModule")).ChangeDisplayedNPC,function() return end)
hookfunction(error, function()end)
hookfunction(warn, function()end)
